#pragma once

#define PACKAGEINFO_PACKAGE_FORMAT_ZIP "zip"

#define PACKAGEINFO_PACKAGE_HASH_ALGO_MD5 "md5"
#define PACKAGEINFO_PACKAGE_HASH_ALGO_SHA1 "sha1"
#define PACKAGEINFO_PACKAGE_HASH_ALGO_SHA224 "sha224"
#define PACKAGEINFO_PACKAGE_HASH_ALGO_SHA256 "sha256"
#define PACKAGEINFO_PACKAGE_HASH_ALGO_SHA384 "sha384"
#define PACKAGEINFO_PACKAGE_HASH_ALGO_SHA512 "sha512"

#define PACKAGE_NAME_VERSION_SEP "-"
#define FILE_NAME_EXT_SEP "."

#define INSTALLER_ARGUMENT_UPDATE "update"
#define INSTALLER_ARGUMENT_WAIT_PID "wait-pid"
#define INSTALLER_ARGUMENT_FORCE_UPDATE "force"
#define INSTALLER_ARGUMENT_SOURCE "source"
#define INSTALLER_ARGUMENT_TARGET "target"
#define INSTALLER_ARGUMENT_LAUNCH_FILE "launch-file"
#define INSTALLER_ARGUMENT_NEW_VERSION "new-version"
