name: macos

on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[no-build]') }}
    name: ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.config }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64]
        config: [debug, release]

    steps:
      - name: Setup python environment
        run: |
          pip install PyYAML

      - name: Setup golang environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v3

      - name: Fetch dependencies
        run: |
          ./fetch_deps

      - name: Fetch gn and ninja
        run: |
          python build/fetch_binaries.py

      - name: Compile
        run: |
          build/bin/gn gen out/${{ matrix.config }}_${{ matrix.arch }} --args="target_cpu=\"${{ matrix.arch }}\" is_debug=${{ matrix.config == 'debug' }}"
          build/bin/ninja -C out/${{ matrix.config }}_${{ matrix.arch }}

      - name: Test
        run: |
          python src/sample/test.py out/${{ matrix.config }}_${{ matrix.arch }}
